Repository Rafael-Morais-D/tn15-pi-grupo01-L, pull requests merged in 2020-07, with the labels that each got.

#2 Aplicando o style.css nas páginas e modais
  config/app.php
  public/css/app.css
  public/css/style.css
  resources/views/index.blade.php
  resources/views/layouts/app.blade.php
Labels: bug, enhancement

#3 Tabela mobile
  public/css/style.css
  resources/views/adm-categoria.blade.php
  resources/views/adm-historico-pedidos.blade.php
  resources/views/adm-mensagem.blade.php
  resources/views/adm-produto.blade.php
  resources/views/adm-usuario.blade.php
  resources/views/user-meus-pedidos.blade.php
  resources/views/user-minha-conta.blade.php
Labels: enhancement

#4 Definindo altura mínima no mobile
  public/css/style.css
Labels: bug

#5 Criando tabela de produtos no banco de dados
  app/Http/Controllers/ProdutosController.php
  app/Produto.php
  config/database.php
  database/migrations/2020_07_16_150840_create_produtos_table.php
Labels: documentation

#7 Criando tabela de mensagens no banco de dados
  app/Mensagem.php
  database/migrations/2020_07_18_175526_create_mensagens_table.php
Labels: documentation

#11 Fazendo autenticação de login administrativo
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/UsuariosController.php
  app/Usuario.php
  public/js/app.js
  resources/views/admin/adm-categoria.blade.php
  resources/views/admin/adm-historico-pedidos.blade.php
  resources/views/admin/adm-mensagem.blade.php
  resources/views/admin/adm-produto.blade.php
  resources/views/admin/adm-usuario.blade.php
  resources/views/admin/formLogin.blade.php
  resources/views/layouts/adm.blade.php
  routes/web.php
Labels: enhancement

#12 DB_Categorias
  app/Categoria.php
  app/Http/Controllers/CategoriasController.php
  database/migrations/2020_07_23_002217_add_comumn_deleted_table_categorias.php
  resources/views/admin/adm-categoria.blade.php
  routes/web.php
Labels: enhancement

#13 Criando o CRUD de usuários
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/CategoriasController.php
  app/Http/Controllers/UsersController.php
  app/Http/Controllers/UsuariosController.php
  app/Usuario.php
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2020_07_16_150840_create_produtos_table.php
  database/migrations/2020_07_17_005321_create_usuarios_table.php
  public/css/style.css
  resources/views/admin/adm-usuario.blade.php
  resources/views/cadastro.blade.php
  resources/views/user-edicao-usuario.blade.php
  resources/views/user-minha-conta.blade.php
  routes/web.php
Labels: enhancement
